import type { Metadata } from 'next'
import ReduxWrapper from './redux-wrapper'
import { Geist_Mono, Poppins } from 'next/font/google'
import './globals.css'

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'The Pops Orchestra',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} ${geistMono.variable} antialiased`}>
        <ReduxWrapper>{children}</ReduxWrapper>
      </body>
    </html>
  )
}
